spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source URL
    url: jdbc:mysql://192.168.0.15:3306/svelte_annual?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    # DB username
    username: root
    # DB password
    password: 1234

mybatis:
  type-aliases-package: com.example.svelte.practice.domain.dto
  mapper-locations: mapper/*.xml